apiVersion: v1
kind: Service
metadata:
  name: kafka-nas-s3-transfer
  namespace: dp03
  labels:
    app: kafka-nas-s3-transfer
    team: dp03
spec:
  type: ClusterIP
  ports:
  - name: health
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: kafka-nas-s3-transfer

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kafka-nas-s3-transfer-pdb
  namespace: dp03
  labels:
    app: kafka-nas-s3-transfer
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: kafka-nas-s3-transfer
